export default {
  imageEditorDisplay: false,
  innerWidth: window.innerWidth,
  showProgress: false,
  uploadingPercentage: 0,
  fileSending: false,
  imageEditorSrc: '',
  buttonsDisplay: 'none',
  navbarDisplay: 'block',
  tui: true,
  images: [],
  selectedImages: [],
  reverse: true,
  sortBy: 'Date',
  deleteModalDisplay: false,
  uploadModalShow: false,
  flkty: null,
  carouselCurrent: '',
};
