
services:

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
      args:
        - PORT=$SERVER_PORT
        - SERVER_URL=$SERVER_URL
        - APP_SECRET=$APP_SECRET
        - JWT_EXPIRATION=$JWT_EXPIRATION
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server/src:/app/server/src
      - ./server/test:/app/server/test

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
      args:
        - REACT_APP_SERVER_URL=$SERVER_URL
        - REACT_APP_CONNECTION_TEST_INTERVAL=$CONNECTION_TEST_INTERVAL
        - PORT=$CLIENT_PORT
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    links:
      - server